databases:
  - name: zaytoon-vdb-db
    plan: free

services:
  - type: web
    name: zaytoon-vdb
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: APP_NAME
        value: Zaytoon VDB
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: zaytoon-vdb-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: zaytoon-vdb-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: zaytoon-vdb-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: zaytoon-vdb-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: zaytoon-vdb-db
          property: password
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_LIFETIME
        value: 10080
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
